### ISSUE TITLE
Include threshold for significant trend to auto generated title or legend

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#10]
**Enhancement.** Trend map allows user to update thresholds for significance (i.e., change p values), but this information is not displayed on the figure. If in legend then maybe something like "Significant Decrease (p<0.05)", Possible Decrease (0.05<p<0.25) where 0.05 and 0.25 are tied to what is entered in the screen.

**Comment by leppott** [comment]
![image](https://user-images.githubusercontent.com/24276278/82052327-72448300-9689-11ea-9fe8-2b7db885d59a.png)

**Comment by jharcum** [comment]
Consider available space when making edit

dialogue box
Threshold (p-value) for 'possible' trend:
Threshold (p-value) for 'significant' trend:

Type of trend
Significant Decrease (p<x.xx) 
Possible Decrease (x.xx<p<x.xx) 


![image](https://user-images.githubusercontent.com/13320765/82074671-1d186980-96a9-11ea-9d45-2e94f9517cd9.png)

**Comment by leppott** [comment]
Adding text as a caption (ggplot2::labs(caption = "foo")).

Not enough space to add to the legend.

![image](https://user-images.githubusercontent.com/24276278/83969587-d29c9e00-a89e-11ea-9e2f-4b1547e760df.png)

**Comment by jharcum** [comment]
any thoughts on including in autogenerated title?

**Comment by leppott** [comment]
Same text in title and caption. 

Caption is always shown.  Title is only when user selects it.

![image](https://user-images.githubusercontent.com/24276278/83972452-2ebaee80-a8ae-11ea-8ec3-8e2a6c65cd10.png)

**Comment by jharcum** [comment]
Tested. Both options are good with me. Leave both in and let client pick.
