### ISSUE TITLE
Correct spelling

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#14]
**Describe the bug**
correct spelling of filter

![image](https://user-images.githubusercontent.com/13320765/82067530-daea2a80-969e-11ea-9a38-893ab488ff29.png)

**Comment by leppott** [comment]
![image](https://user-images.githubusercontent.com/24276278/83151668-dc6a1880-a0ca-11ea-9cb2-c3b7f98b4082.png)
