### ISSUE TITLE
table title

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#15]
**Describe the bug**
Change Table 3 to "Table 2. Station summary"
Change Table 2 to "Table 3. Filtered data"

![image](https://user-images.githubusercontent.com/13320765/82068403-eee25c00-969f-11ea-85f1-514102dc1473.png)

![image](https://user-images.githubusercontent.com/13320765/82068674-4b457b80-96a0-11ea-8cf7-bd3005bf7ce5.png)

**Comment by leppott** [comment]
![image](https://user-images.githubusercontent.com/24276278/83142824-06b5d900-a0bf-11ea-9957-1dd7a8e2234f.png)

![image](https://user-images.githubusercontent.com/24276278/83142851-10d7d780-a0bf-11ea-8b3b-e0aa8429f0b1.png)
