### ISSUE TITLE
Navigation bar title for range map and trend map

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#16]
**Describe the bug**
Change "3.a. Range Map Options" to Change "Range Map Options" 
Change "3.b. Trend Map Options" to Change "Trend Map Options" 

![image](https://user-images.githubusercontent.com/13320765/82068932-a6776e00-96a0-11ea-9cee-6b2298be0236.png)

![image](https://user-images.githubusercontent.com/13320765/82068999-bee78880-96a0-11ea-97cf-c6b993410974.png)

**Comment by leppott** [comment]
![image](https://user-images.githubusercontent.com/24276278/83141437-affbcf80-a0bd-11ea-9073-650455d41879.png)

![image](https://user-images.githubusercontent.com/24276278/83141461-bab66480-a0bd-11ea-825e-2f6ed971cef5.png)
