### ISSUE TITLE
Filter Data Summary tab wording

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#17]
**Describe the bug**
change wording of "entries" to "stations" where indicated.

![image](https://user-images.githubusercontent.com/13320765/82070483-cd36a400-96a2-11ea-8ab0-4722f1b9a4d2.png)

**Comment by leppott** [comment]
"entries" text on the DT::renderDT should be able to be edited.

https://stackoverflow.com/questions/45085026/how-to-change-datatables-text-showing-page-1-of-5-of-x-entries

**Comment by leppott** [comment]
It is possible to change some of the text under the table the word "entries" is not editable.  (Though you can change the language).

**Comment by jharcum** [comment]
No one commented on this ... let's close this unless someone else brings it up.
