### ISSUE TITLE
Revise workflow for loading and sorting data

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#19]
**Describe the solution you'd like**
See attached mock up 
[Baytrends app.pdf](https://github.com/tetratech/baytrendsmap/files/4657914/Baytrends.app.pdf)

**Comment by jharcum** [comment]
Example rda and csv files of split out data. See rda for df = fileList for list of files, data frame names, and radio button names.  
[baytrendsmap_2018_data.zip](https://github.com/tetratech/baytrendsmap/files/4658012/baytrendsmap_2018_data.zip)

**Comment by jharcum** [comment]
Updated example rda and csv files of split out data. See rda for df = fileList for list of files, data frame names, and radio button names.

[baytrendsmap_2018_data,R1.zip](https://github.com/tetratech/baytrendsmap/files/4713907/baytrendsmap_2018_data.R1.zip)

**Comment by jharcum** [comment]
data files in previous comment meet minimum data requirements specified [here](https://github.com/tetratech/baytrendsmap/issues/7)

**Comment by leppott** [comment]
Should decide on file names and screen select values so can change the data without updating the app.

![image](https://user-images.githubusercontent.com/24276278/84404702-2ed02c80-abd5-11ea-9af8-2897dd54ea84.png)

![image](https://user-images.githubusercontent.com/24276278/84404736-38f22b00-abd5-11ea-858c-fff81da4f962.png)

**Comment by leppott** [comment]
New data files tested with filters.  And new column contents come through fine.

![image](https://user-images.githubusercontent.com/24276278/84422586-40243380-abeb-11ea-8eaf-ecf9c9ff9f05.png)

**Comment by leppott** [comment]
v1.0.0.9020 adds radio buttons for files saved within the app.

The first radio button is default and that file is auto loaded.

Selecting other radio buttons will change the loaded file.

Changed the wording slightly for headers.

**Comment by jharcum** [comment]
Looks good. I’d say get that 2nd page of workflow going

Jon Harcum, PhD | Principal Engineer/Hydrologist | Tetra Tech
Direct (864) 650-5815 | jon.harcum@tetratech.com

This message, including any attachments, may include privileged, confidential and/or inside information. Any distribution or use of this communication by anyone other than the intended recipient is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by replying to this message and then delete it from your system.

**Comment by leppott** [comment]
Added "reset" button for file input but it isn't active.

If select a user file the input doesn't clear so can't select a presaved file.

Renamed long file names otherwise get a warning when build the package that it won't work on some systems due to file path > 100 characters.  Defined in global.R.

pick_files_radio <- c("Non-linear Trend (Full Period)"
                      , "Non-linear Trend (2009-2010 to 2017-2018)"
                      , "Non-linear Trend with Flow Adjustment (Full Period)"
                      , "Non-linear Trend with Flow Adjustment (2009-2010 to 2017-2018)")
pick_files_names <- c("Trend_NL_FA_F_Full.csv"
                      , "Trend_NL_FA_F_Short.csv"
                      , "Trend_NL_FA_T_Full.csv"
                      , "Trend_NL_FA_T_Short.csv")

**Comment by leppott** [comment]
For filters will need to modify "Reset Filters" button since using UIoutput for different set of filters based on file type.

**Comment by leppott** [comment]
Filter UI changes based on whether "user" or "official" file.  "Official" shown below.

For now is a select input.  Once get other items working (with 2 sets of filters need to tweak other items) then will try for radio buttons.  Mixing radio buttons and select input will require further tweaks.

![image](https://user-images.githubusercontent.com/24276278/84524634-47f5dd80-aca8-11ea-9b0e-81777133e09e.png)

**Comment by leppott** [comment]
Leave mapLayer as selectInput rather than radio buttons.  24 options is too many.

![image](https://user-images.githubusercontent.com/24276278/84525726-20077980-acaa-11ea-8afe-89372df931a6.png)

**Comment by leppott** [comment]
Scrapped the radio buttons as taking up too much space.  Redesigned selectizeInput() as selectInput() and now have a single pull down list.  The list of variables is dependent upon the imported file.  This list is unsorted and listed in the order of appearance in the file.  So it could be that parameters are not all together.

![image](https://user-images.githubusercontent.com/24276278/84538435-a7131c80-acbf-11ea-85d4-f0f2f961f62a.png)

**Comment by leppott** [comment]
Revisit auto-generate map titles with "official" data.  

filters replaced with mapLayer.

![image](https://user-images.githubusercontent.com/24276278/84539735-f78b7980-acc1-11ea-9ab2-942ecd1baa38.png)

**Comment by leppott** [comment]
Set the Map Layer collapse to OPEN so user will always see it.

**Comment by leppott** [comment]
Range Map

![image](https://user-images.githubusercontent.com/24276278/84542228-00327e80-acc7-11ea-938e-e3bdd22d7934.png)

Trend Map

![image](https://user-images.githubusercontent.com/24276278/84542385-58698080-acc7-11ea-9cdd-b7d1d279a46e.png)

**Comment by leppott** [comment]
Still to fix:

- [ ] Reset Filters button

- [ ] Select official file with radio buttons after selecting user file with browse button

- [ ] Filter Data Summary.  1. # records and 2. table

- [ ] Filter Data.  Doesn't show for user file after selecting official file from radio buttons.

**Comment by leppott** [comment]
Turned off 'reset files' button.  Easiest to use "F5" to restart shiny and clear the file names.

Clear filters fixed.

**Comment by jharcum** [comment]
How will this play out when loaded on CBP’s AWS site?

Jon Harcum, PhD | Principal Engineer/Hydrologist | Tetra Tech
Direct (864) 650-5815 | jon.harcum@tetratech.com

This message, including any attachments, may include privileged, confidential and/or inside information. Any distribution or use of this communication by anyone other than the intended recipient is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by replying to this message and then delete it from your system.

**Comment by leppott** [comment]
Save internal reactiveValues and keep track of the last button clicked (official vs. user).

Use that value to determine data to load.

Appears to be working.

Can also display to the user.

![image](https://user-images.githubusercontent.com/24276278/84691717-99090a00-af12-11ea-8daa-01b3f9428b92.png)


![image](https://user-images.githubusercontent.com/24276278/84691755-a8885300-af12-11ea-83e3-8a36ab231adf.png)

Cannot easily clear the "browse" button but can keep track of the last file loaded.  So if click "official" after a "user" file the data changes.  And the text for "loaded file type" changes.

![image](https://user-images.githubusercontent.com/24276278/84691859-db324b80-af12-11ea-8077-5ce3c3fceffc.png)

**Comment by leppott** [comment]
Modified timing of filters.

Added error message for no data selected.

![image](https://user-images.githubusercontent.com/24276278/84807407-3167c300-afd5-11ea-8fd1-d96509aaa9e9.png)

**Comment by jharcum** [comment]
Is this issue ready to close?
