### ISSUE TITLE
1. load data tab name

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#20]
**Describe the solution you'd like**
+ Relabel "1. Load Data" to "1. Select Data"
+ Make this tab the home tab instead of the help tab

![image](https://user-images.githubusercontent.com/13320765/82468278-9d1b4680-9a90-11ea-80df-a18b5c6f1f2d.png)

**Comment by leppott** [comment]
![image](https://user-images.githubusercontent.com/24276278/83139950-38c53c00-a0bb-11ea-87d3-a68b4718387e.png)
