### ISSUE TITLE
packages not loaded

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#22]
**Describe the bug**
**Per Breck 5/22 email:** For it to work, I needed to upload a lot of packages that I wasn’t aware of until I got error and error after trying to run the library(baytrendsmap).

**Comment by leppott** [comment]
Checked package and all packages needed are listed in DESCRIPTION

Though there are 2 packages listed under "Suggests".  These should not be needed for basic operation of the baytrendsmap package.  And the default for devtools::install_github has dependencies = NA so these are not installed.

Will update README to include dependencies = TRUE to ensure all packages in DESCRIPTION are installed.

**Comment by leppott** [comment]
Also change README install example repo from from leppott\baytrendsmap to tetratech\baytrendsmap

**Comment by jharcum** [comment]
Tested. Install  appears to do needed updates (I too had a couple of sporadic issues, but dont believe it is a baytrendsmap issue)
