### ISSUE TITLE
Collapse for filters and maps all closed - some need to be open for "apply" buttons to work

### ISSUE THREAD

**Issue by leppott** [tetratech/baytrendsmap#23]
**Is your feature request related to a problem? Please describe.**
Some of the filters need to be opened in order for the "apply filters".

And same with the maps.

**Describe the solution you'd like**
It would be good to have these panels open rather than closed.

**Describe alternatives you've considered**
Not sure if should implement as it takes up much more screen real estate.

**Additional context**
![image](https://user-images.githubusercontent.com/24276278/83163233-cebb8f80-a0d8-11ea-8fea-7f3ab481f89a.png)

**Comment by leppott** [comment]
Put in placeholders in the code in case need to implement.

![image](https://user-images.githubusercontent.com/24276278/83163422-00345b00-a0d9-11ea-94ff-d49505dd3f1e.png)

**Comment by leppott** [comment]
Modified timing of filters.

Added error message for no data selected.

![image](https://user-images.githubusercontent.com/24276278/84807407-3167c300-afd5-11ea-8fd1-d96509aaa9e9.png)

**Comment by jharcum** [comment]
Let's roll with current look and feel.

**Comment by leppott** [comment]
Maps can fail to generate if don't make selections.

Add ifelse code to change from NULL to defaults.

var = baseline mean
classInt = pretty
pal = PuOr
extension = png
rivernames = Yes
good direction  = TRUE

**Comment by leppott** [comment]
![image](https://user-images.githubusercontent.com/24276278/87575607-28364880-c69e-11ea-9fa8-043f7ddc9cb9.png)
