### ISSUE TITLE
Increase file upload size

### ISSUE THREAD

**Issue by leppott** [tetratech/baytrendsmap#25]
**Is your feature request related to a problem? Please describe.**
Testing some of the files that were delivered from Renee and Mike, I did run into a max size exceeded for the CSV files.  It seems to be around 10MB? Many of their files are bigger than that, due to all the options you can put into a change file.  Any chance we can increase the limit, or perhaps put a note  saying (“Max size…”).  It’s easy enough to cut them down in excel, but helpful to know what it is. 

**Describe the solution you'd like**
Increase max file size from 10 to 100 MB.
And add note for max size.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by leppott** [comment]
![image](https://user-images.githubusercontent.com/24276278/85047747-4329a180-b160-11ea-8224-2273d62bee19.png)

**Comment by leppott** [comment]
Move text to the correct location.

![image](https://user-images.githubusercontent.com/24276278/85133562-ec2bd700-b208-11ea-8510-a687d6e383c2.png)

**Comment by jharcum** [comment]
seems to load a plenty large file ...

**Comment by jharcum** [comment]
opps ... still need to move text to the correct location

**Comment by jharcum** [comment]
location of text added to issue #31 ... so this issue is obsolete.
