### ISSUE TITLE
baytrendsmap data

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#26]
**Additional context**
From Murphy (6/18/2020) #2. Could the Season specifier in the mapLayer list that is currently “Jan-Dec” be changed to “Annual”?  

JH: Updated data attached. (Also includes dropping SUMMER2 water temperature and secchi)

[baytrendsmap_2018_data,R2.zip](https://github.com/tetratech/baytrendsmap/files/4805560/baytrendsmap_2018_data.R2.zip)

**Comment by jharcum** [comment]
**Next**
Load attached data into baytrendsmap tool

**Comment by leppott** [comment]
Added files to the shiny app.

Did not use "raw-data" folder.

```
# baytrendsmap 
# Final Files
# Updates, Issue #26
# https://github.com/tetratech/baytrendsmap/issues/26
# 2020-06-29
# Erik.Leppo@tetratech.com

dn_in <- "C:\\Users\\Erik.Leppo\\OneDrive - Tetra Tech, Inc\\MyDocs_OneDrive\\_HOME\\COVID19\\baytrends\\Data_Issue26"
fn_in <- list.files(dn_in, "csv$")

# [1] "Non-linear Trend (2009-2010 to 2017-2018).csv"                     
# [2] "Non-linear Trend (Full Period).csv"                                
# [3] "Non-linear Trend with Flow Adjustment (2009-2010 to 2017-2018).csv"
# [4] "Non-linear Trend with Flow Adjustment (Full Period).csv" 

fn_out <- c("Trend_NL_FA_F_Short.csv"
          , "Trend_NL_FA_F_Full.csv"
          , "Trend_NL_FA_T_Short.csv"
          , "Trend_NL_FA_T_Full.csv")

file.copy(file.path(dn_in, fn_in)
          , file.path("inst", "shiny-examples", "baytrendsmap", "data", fn_out)
          , overwrite = TRUE)
```

![image](https://user-images.githubusercontent.com/24276278/86047604-1d808000-ba1d-11ea-8e8d-9561f2fc166f.png)

**Comment by jharcum** [comment]
review completed. done.
