### ISSUE TITLE
auto generate title

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#27]
**Describe the bug**
for 'final files" the auto generate title uses an abbreviation (probably pulled out of maplayer. Instead let's use the full parameter name from "parmName"

![image](https://user-images.githubusercontent.com/13320765/85162179-e5b05600-b22e-11ea-8be7-80936cdabd75.png)

**Comment by leppott** [comment]
Parsed maplayer which has the short name.  Need to use parmName.

![image](https://user-images.githubusercontent.com/24276278/86036608-2452c700-ba0c-11ea-8726-e47ca5768515.png)

**Comment by leppott** [comment]
Update titles using a reference to the filtered data.

**Map, Range**
![image](https://user-images.githubusercontent.com/24276278/86037647-b0192300-ba0d-11ea-80c7-a91f35f0989c.png)

**Map, Change**
![image](https://user-images.githubusercontent.com/24276278/86037754-e060c180-ba0d-11ea-873e-ce115e8fdb37.png)

**Comment by leppott** [comment]
**Map, Range**
![image](https://user-images.githubusercontent.com/24276278/86038154-7d235f00-ba0e-11ea-99a2-2edd1e1a748e.png)

**Map, Change**
![image](https://user-images.githubusercontent.com/24276278/86038123-6f6dd980-ba0e-11ea-80d3-dee076789a32.png)

**Comment by jharcum** [comment]
Final files autogenerate correct titles.  However, "**user files**" do not appear to correctly create the parameter and model entries

**Comment by jharcum** [comment]
Final files autogenerate correct titles. However, "user files" do not appear to correctly create the parameter and model entries

**Comment by leppott** [comment]
Revised "user files" to use same format as "final" files.

![image](https://user-images.githubusercontent.com/24276278/86161054-b4f7d880-bada-11ea-9809-89b67b22fcf6.png)

**Comment by jharcum** [comment]
Done. Closed.

**Comment by jharcum** [comment]
Parameter, GAM model, and Layer do not load with auto-generate title (see image). Procedure to reproduce:

- load attached zip file.
- go to filter data and select one period and one season.
- click apply filter,
- go to range map, 
- click auto-generate.

[ComboChngFile_2018_chla_sortBYstation.zip](https://github.com/tetratech/baytrendsmap/files/4878773/ComboChngFile_2018_chla_sortBYstation.zip)

![image](https://user-images.githubusercontent.com/13320765/86592203-01bb3380-bf61-11ea-973a-6191474d324a.png)

**Comment by leppott** [comment]
Change code to use to filter data frame, df_filt(), that will have the results from "apply filter" button.  Current code was split using some from df_filt() (final file) and other using the selectInput boxes (user file).  This resulted in some cases where made a selection and had not hit "apply filter" and things got out of sync. Also, if generate title before doing all boxes got blanks (since selectInput boxes where not active and were null).

**Comment by jharcum** [comment]
done
