### ISSUE TITLE
Cannot load csv file if not sorted by station

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#28]
**Describe the bug**
App doesn't load user files not sorted by station.  

**to repeat**
Attached are 2 csv files, sorted by station and period name, respectively; otherwise they are the same data. the *sortBYstation.csv" file works and the other does not.
[chngGAM.zip](https://github.com/tetratech/baytrendsmap/files/4813782/chngGAM.zip)

**Comment by jharcum** [comment]
cannot reproduce now.  moved to on hold

**Comment by leppott** [comment]
Modified filters to sort the entries for all files.

![image](https://user-images.githubusercontent.com/24276278/86164426-c0013780-badf-11ea-926b-203b4be002d7.png)

If had an unsorted file the entries in the filters appeared in the order of the the file..

![image](https://user-images.githubusercontent.com/24276278/86164334-99db9780-badf-11ea-99d7-9ab90117b5d5.png)

**Comment by leppott** [comment]
Also have to update server.R output$filter_x for each parameter by adding sort().

![image](https://user-images.githubusercontent.com/24276278/86166814-67cc3480-bae3-11ea-8da1-538041970ddf.png)

**Comment by jharcum** [comment]
Works now.
