### ISSUE TITLE
Update help file

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#29]
**Describe the bug**
Update help file

**Comment by jharcum** [comment]
ShinyHelp.Rmd has been updated and pushed to github; however, app still appears to grab the old version of the help file. Need higher level response.

**Comment by leppott** [comment]
Running "\raw-data\ProcessRMD_ShinyHelp.R" knits and copies the file to the shiny www folder.

Manually moved ShinyHelp.html from raw-data to www.

Works.

![image](https://user-images.githubusercontent.com/24276278/86033684-5877b900-ba07-11ea-9947-f73f441f0c55.png)

**Comment by jharcum** [comment]
Reviewed. Done,
