### ISSUE TITLE
Trend map produces NA in legend

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#30]
**Describe the bug**

**To Reproduce**
1. load non-linear trend (full period)
2. select "chla|Surface|Jul-Sep"
3. select filter
4. note station CB7.4N has baseline mean of 1.647038295
5. do range map of basline mean with interval='quantile'
6. observe that legend uses "(1.65,5.8] ... " and station at CB mouth (pennisula side) is open

**Expected behavior**
I think "(1.65,5.8] should be "**[**1.65,5.8]

**Comment by jharcum** [comment]
Possibly tied to issue #8

**Comment by leppott** [comment]
For range map add ", include.lowest = TRUE" to cut function in server.R.

![image](https://user-images.githubusercontent.com/24276278/86171839-61da5180-baeb-11ea-9cfd-7d723f3a23cd.png)


**OLD**
![image](https://user-images.githubusercontent.com/24276278/86171979-a82fb080-baeb-11ea-89f0-ed3189aa32a8.png)

**REVISED**
![image](https://user-images.githubusercontent.com/24276278/86172143-e75e0180-baeb-11ea-92d6-a9c08a6fd2d2.png)

**Comment by jharcum** [comment]
Done.
