### ISSUE TITLE
Opening page typos

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#31]
**Expected behavior**
changes

- [ ] 1: change to "1a. Load final file"
- [ ] 2: change to "Load 'Final' File"
- [ ] 4. change to "2. Filtered Data"
- [ ] 3: move statement about "Maximum file size is 100 MB." as shown. Could put in "( )" as depicted or as a separate line, either above or below the Browse dialogue box. 

![image](https://user-images.githubusercontent.com/13320765/85454423-eae10e00-b56a-11ea-8b43-9821e3d9ea0a.png)

**Comment by leppott** [comment]
tab_Data.R

"Filtered Data" tab is Issue #32

**Comment by leppott** [comment]
Prefer "max 100 mb" as button title over text below the button.  Will use the button title over the below button text.

![image](https://user-images.githubusercontent.com/24276278/85601192-27207700-b61c-11ea-815f-4ce81d58d16b.png)

**Comment by jharcum** [comment]
QC complete
