### ISSUE TITLE
Filter page typos

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#32]
**Expected behavior**

- [x] 1: change wording to "Filtered Data Summary"
- [x] 2: change wording to "Filtered Data"
- [x] 3: change wording to:
The number of unique entries by station are in the table below. Modify filters and click **Apply Filters** if value is greater than one.
For 'final' files, the only field that requires filtering is **Map Layer**.
For user-created files, you may need to filter by 'Parameter', 'GAM', 'Layer', 'Period', and 'Season'.
- [x] 5: change wording to: "Change Map"
- [x] 4: ERIK: FOR discussion: Client stated: Is there any way the “Apply Filters” and “Reset Filer Selections” button locations can be switched?  If I want to reset, I have to scroll down to click the “Reset” button before scrolling back up to make new selections.  Then it seem strange after making the selections to have to scroll back up to hit the “Apply” button.   Harcum: Either do what client says or consider putting both buttons at the top, side-by-side

![image](https://user-images.githubusercontent.com/13320765/85604316-2fc67c80-b61f-11ea-9f1f-fddc6eff3740.png)

**Comment by leppott** [comment]
Better to stack the buttons.

On large screens buttons ok side by side.

![image](https://user-images.githubusercontent.com/24276278/85575348-7ad39600-b605-11ea-8327-2467fa6904fd.png)

But if make the window small the buttons overlap.

![image](https://user-images.githubusercontent.com/24276278/85575449-8fb02980-b605-11ea-8be4-c04de5230d65.png)

**Comment by leppott** [comment]
Change tab name to "Filtered Data".

Issue #31

**Comment by jharcum** [comment]
See task 4 ... to change "Trend Map" to "Change Map" in tab title (I was probably editing this issue while you were fixing it - which is why it was probably missed)

**Comment by jharcum** [comment]
Reviewed. Done.
