### ISSUE TITLE
Trend map -> Change map wording

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#33]
**Expected behavior**
Change 8 locations from "Trend" to "Change"

![image](https://user-images.githubusercontent.com/13320765/85605412-212c9500-b620-11ea-8206-535918c7b0b3.png)

**Comment by leppott** [comment]
Tab name is also on Issue #32

**Comment by leppott** [comment]
Updated image below.

![image](https://user-images.githubusercontent.com/24276278/86010201-0fb10780-b9e9-11ea-9e4f-c0c7f592bd2e.png)

**Comment by leppott** [comment]
Left "trend" name on variables and parameters in the code.  Only the parts visible to the user (i.e., text on screen) were modified to "change".

**Comment by jharcum** [comment]
... crap ... change the remaining "Trend" to "Change" also (not sure how i missed it.)

**Comment by leppott** [comment]
![image](https://user-images.githubusercontent.com/24276278/86156461-fc2e9b00-bad3-11ea-9bb7-6267ad7d506e.png)

**Comment by jharcum** [comment]
Done. Closed.

**Comment by leppott** [comment]
Forgot about some back-end items including the default filename when save/download includes "trend".  Updated to "change".
