### ISSUE TITLE
Loaded file type

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#35]
**Describe the bug**
On Select data page when user selects a final file, the "Loaded file type =official". Change to "Loaded file type =final" for consistency.

![image](https://user-images.githubusercontent.com/13320765/86592384-5c548f80-bf61-11ea-96cf-7df9a4381757.png)

**Comment by leppott** [comment]
Fixed display in server.R and in all the triggers for other events.

![image](https://user-images.githubusercontent.com/24276278/86613601-d72ca300-bf7f-11ea-9bad-5381556b1d60.png)

**Comment by jharcum** [comment]
Done
