### ISSUE TITLE
Change map legend

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#36]
Change map legend looks good online (symbols do not overlap shoreline boundary or station locations *and* km in scale is fully visible). However once the file is saved, the legend overlaps eastern shore boundary and the 'm' in km is partically cut off.

Are there options to improve the downloaded file without sacrificing current online size  and layout? (If not, let's keep it 'as is.)

![image](https://user-images.githubusercontent.com/13320765/86593015-7b075600-bf62-11ea-8f68-d12d2cebb4d9.png)

![map_trend_20200706_074418](https://user-images.githubusercontent.com/13320765/86592921-4bf0e480-bf62-11ea-9088-5ffe4e21382a.png)

**Comment by leppott** [comment]
Changing the size of the plot (height and width within ggsave) does not make a difference.

Need to use "scale" within ggsave.  To change the relative size of the text to the plot. Larger value is smaller text.  Default is 1.

**scale = 1** (same as above)
![image](https://user-images.githubusercontent.com/24276278/86632093-f4239f00-bf9c-11ea-8915-7683e1eb7f18.png)

**scale = 0.5**
![image](https://user-images.githubusercontent.com/24276278/86632045-e706b000-bf9c-11ea-8fdd-3bc79df90633.png)

**scale = 2.0**
![image](https://user-images.githubusercontent.com/24276278/86631965-c9d1e180-bf9c-11ea-96ed-6610745fd9ca.png)

**scale = 1.5**

**scale = 1.25**

**Comment by leppott** [comment]
Use scale = 1.25 with height of 9 (same as before) and width of 9/1.3.

1.3 is used in the plot for coord_fixed().

This results is a size of 9 * 6.92.

**Comment by leppott** [comment]
Final versions.

![image](https://user-images.githubusercontent.com/24276278/86633687-f7b82580-bf9e-11ea-85d0-8c27a862aa54.png)

![image](https://user-images.githubusercontent.com/24276278/86633704-fe469d00-bf9e-11ea-8d28-e4a6d9868889.png)

**Comment by jharcum** [comment]
current version looks good.
