### ISSUE TITLE
filter window doesn't display entered information

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#39]
**Describe the bug**

- [x] Filter windows do not display entered information. (The windows appear to work as I am able to blindly type "LE" into the station filter window and the table will filter down ... just cannot see what i typed.

![image](https://user-images.githubusercontent.com/13320765/87160994-e0748300-c291-11ea-906e-4d3e1172182d.png)

**Comment by leppott** [comment]
Column width is the issue here.

Will have to specify the column width by column number and not name.

May need to do for only a few columns since can have different formats (user and final).

**Comment by leppott** [comment]
Set up default column width of "200px" in global.R.

Set up eventreactive for import and filter data tables.  To check certain columns and define index values.

When generate DT check the index values above and set the width to a manual value.

**OLD**
Column not wide enough to see entries.
![image](https://user-images.githubusercontent.com/24276278/87704184-05716600-c76a-11ea-940f-b7bcef3d7a52.png)


**NEW**
Takes up more screen space but have a scroll bar.
![image](https://user-images.githubusercontent.com/24276278/87704289-2fc32380-c76a-11ea-8e99-dfa54c0885eb.png)

**Comment by jharcum** [comment]
done
