### ISSUE TITLE
Load user file

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#40]
**Describe the bug**
Cannot load user file not sorted by station

**To Reproduce**
1. Open baytrends map from https://leppott.shinyapps.io/baytrendsmap/
2. Click on Browse
3. Select attached file (ComboChngFile_2018_chla_sortBYperiodName.csv)
4. See error in below screen capture
5. Loaded same content but sorted by station works (ComboChngFile_2018_chla_sortBYstation.csv)

**Error with: ComboChngFile_2018_chla_sortBYperiodName.csv**
![image](https://user-images.githubusercontent.com/13320765/87163247-0cddce80-c295-11ea-8d81-65d3f1b58370.png)

**No error with: (ComboChngFile_2018_chla_sortBYstation.csv**
![image](https://user-images.githubusercontent.com/13320765/87163354-30a11480-c295-11ea-91e5-c4d2c66a7d19.png)

[ComboChngFile_2018_chla_sortBYperiodName.zip](https://github.com/tetratech/baytrendsmap/files/4903571/ComboChngFile_2018_chla_sortBYperiodName.zip)
[ComboChngFile_2018_chla_sortBYstation.zip](https://github.com/tetratech/baytrendsmap/files/4903572/ComboChngFile_2018_chla_sortBYstation.zip)

**Comment by leppott** [comment]
Works fine when run locally.  Only have issue when run remote on Shiny.io servers.

Unable to track down the exact cause.  Resorting the file or removing the bad entries fixes the issue.

Added text to the help file.

![image](https://user-images.githubusercontent.com/24276278/87708634-08bc2000-c771-11ea-8db3-7c9665867fd5.png)

**Comment by jharcum** [comment]
done.
