### ISSUE TITLE
Add documentation about what the data are

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#42]
**Describe the solution you'd like**
Add a description of the data housed in baytrendsmap

**Additional context**
Participants recommended at ad hoc modeling workgroup (7/14/2020) that description be added

**Comment by leppott** [comment]
https://github.com/tetratech/baytrendsmap/commit/60948d54f78e2b4a6f5d018f9f664eabc03b6f9d

Update to help and other description files for basic interface.

**Comment by jharcum** [comment]
done
