### ISSUE TITLE
12.29.2020 action items

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#45]
**Additional context**
+ update version number to v1.2.0
+ push version to CBP for posting on their server
+ create a release called "CBP 2019 Trends"
+ rename the existing release "CBP July 2020 Release" as "CBP 2018 Trends"

**Comment by leppott** [comment]
Renamed old release.

Some clean up from CMD check and lintr check.

**Comment by leppott** [comment]
Done.

Did some minor clean up (CMD check).  Added GitHub Actions for CMD check and pkgdown (adds new branch and autobuilds the weblink after each submittal).  Added some basic badges to the README so shows up on the website and on the main GitHub page.

**Comment by leppott** [comment]
Commit v1.2.0  
https://github.com/tetratech/baytrendsmap/commit/cbe77d181b488cfa60e9b98f4f30a3b24fe99f7d

Release
https://github.com/tetratech/baytrendsmap/releases/tag/v1.2

**Comment by leppott** [comment]
Added new release with the additional color palette options.
https://github.com/tetratech/baytrendsmap/releases/tag/v1.2.1

**Comment by jharcum** [comment]
concur
