### ISSUE TITLE
Potential gam4 plot and external csv file architecture

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#50]
- [x] Although not pushing out "gam4" plots near term, we should consider whether/when to build the architecture to handle flow adjusted results in this revision even though we do not populate it with plots at this time. 

- [x] Consider moving csv files that we have pre-loaded in the package to be external as we have done with the pop-up plots.  (If we do this, we'll need to consider how to make the radio buttons on tab 1a dynamic.)

**Comment by leppott** [comment]
Part 2 as Issue #54

**Comment by leppott** [comment]
Rename plots folder "nlt_fp" to "plots_NLT_FA_F_FP" to match data file naming.

![image](https://user-images.githubusercontent.com/24276278/133452062-be3e9168-db30-427a-bac1-13ebdcce54f9.png)

**Comment by leppott** [comment]
Update Shiny app to use new plots folder.

Issue #54

**Comment by jharcum** [comment]
this seems done
