### ISSUE TITLE
Range map only shows bins that have data

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#51]
**Describe the bug**
If bins are specified for the range map, then all bins should be assigned a color. This will facilitate comparison of range maps for two different time periods.

**To Reproduce**
1. select 'Non-linear Trend (full period)'
2. filter to surface TN annual
3. go to plot **baseline mean** in range map
4. set Custom classes (comma delimited) to:  .2, .4, .8, 1, 1.5, 2, 3, 5, 8 
5. set color palette to "OrRd" 
6. save figure
7. Repeat the above but use **current mean**
8. save figure

**Issue**
Notice the difference in the legend. since current mean max value is <3, the last two bins 3-5 and 5-8 are not shown; however, the 2-3 bin takes on the darkest color (same as baseline mean of 5-8).  So this makes a visual comparison more difficult.

**Desired behavior**
If user specifies bins then display all specified bins even if there are no observations

**Screenshots**
![image](https://user-images.githubusercontent.com/13320765/127043414-1dec834e-22ae-4ba9-8ac1-0df433031c77.png)

**Comment by leppott** [comment]
Use "drop = FALSE" inside of scale_fill_brewer() in server.R when creating/updating range map.

**Comment by leppott** [comment]
![map_range_20210809_144148_baseline](https://user-images.githubusercontent.com/24276278/128757499-0271a12b-5960-4801-a5f6-4b95ca958382.png) ![map_range_20210809_144239_Current](https://user-images.githubusercontent.com/24276278/128757538-1a8cf2ed-90f3-495b-8187-c81c33da87a4.png)

**Comment by leppott** [comment]
Update in development branch.  Can close once review and then merge in to main branch.

**Comment by leppott** [comment]
Confirmed the dynamic (leaflet) map works fine (shows all 8 categories) for current mean.

![image](https://user-images.githubusercontent.com/24276278/129762102-75115ba1-7959-4509-a511-c09ef327c433.png)
