### ISSUE TITLE
pop up text

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#59]
**text for popup**

This app provides access to maps depicting short- and long-term changes, or trends, in nutrients, dissolved oxygen (DO), Secchi depth (a measure of clarity), and chlorophyll-a at more than 130 stations located throughout the mainstem of the Chesapeake Bay and the tidal portions of numerous tributaries on the western and eastern shores since the mid-1980s. Click HELP in main menu for information on how to use this app.

**Comment by leppott** [comment]
Use `shinyalerts::shinyalert()` as nicer than the basic `shiny::modalDialog()` and `shiny::showModal()`.

Also shinyalert is center center with more formatting.  showModal is center top.

**shinyalert**
![image](https://user-images.githubusercontent.com/24276278/168072529-258ebade-55f7-4c3e-9e4f-0ee9bbf0e0e8.png)

**showModal**
![image](https://user-images.githubusercontent.com/24276278/168072769-822bf1b4-cbfa-4332-b414-f7d2ff732012.png)
