### ISSUE TITLE
Background window

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#60]
**replacement text for background page**

Maryland Department of Natural Resources (MDDNR), Virginia Department of Environmental Quality (VADEQ), the District of Columbia, and others have coordinated to sample water quality on a bi-monthly or monthly basis at more than 130 stations located throughout the mainstem of the Chesapeake Bay and the tidal portions of numerous tributaries on the western and eastern shores since the mid-1980s. Scientists evaluate short- and long-term changes, or trends, in nutrients, dissolved oxygen (DO), Secchi depth (a measure of clarity), and chlorophyll-a using a Generalized Additive Modeling (GAM) approach.

The approach includes selecting a GAM structure to describe nonlinear seasonally-varying changes over time, incorporation of hydrologic variability via either river flow or salinity, the use of an intervention to accommodate method or laboratory changes suspected to impact data values, and representation of left- and interval-censored data (Murphy et al, 2019, 2021). 

Selected results can be found here: pdf link

Murphy, R.R., E. Perry, J. Harcum, and J. Keisman. 2019. A generalized additive model approach to evaluating water quality: Chesapeake Bay case study. Environmental Modeling and Software 118(August 2019):1-13.

Murphy, R, E. Perry, J. Keisman, J. Harcum, and E. Leppo. 2021. baytrends: Long Term Water Quality Trend Analysis. R package version 2.0.5.https://CRAN.R-project.org/package=baytrends.

**Comment by leppott** [comment]
done.

![image](https://user-images.githubusercontent.com/24276278/168106287-ffeb3847-2a90-4048-acf8-545d05ae0a7d.png)

**Comment by leppott** [comment]
modify link with target = "_blank" so opens in a new window.
