### ISSUE TITLE
Popup - change icon image

### ISSUE THREAD

**Issue by leppott** [tetratech/baytrendsmap#61]
**Is your feature request related to a problem? Please describe.**
Change image/icon for popup.

**Describe the solution you'd like**
Change icon.

**Describe alternatives you've considered**
Maybe use awesome font info with imageURL rather than type = info.

![image](https://user-images.githubusercontent.com/24276278/176675221-23c2e2d9-5064-403d-8f65-9ebe9cf0ef09.png)

**Additional context**
Code is in the server.R file and is implemented with `shinyalert`, type = "info".  Should be able to use a custom image.  Maybe from 

![image](https://user-images.githubusercontent.com/24276278/176674747-74e4ce01-7dbb-4c81-a09c-2d3c84ab5f85.png)

![image](https://user-images.githubusercontent.com/24276278/176675010-77103227-2b99-4b16-a1b6-ecc1184f1d76.png)

**Comment by jharcum** [comment]
looks good

**Comment by jharcum** [comment]
looks good
