### ISSUE TITLE
Initial popup screen bolding

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#62]
**Is your feature request related to a problem? Please describe.**
Make highlighted text on initial pop up screen bold

**Additional context**
See below popup for details
![image](https://user-images.githubusercontent.com/13320765/178359226-adc43ff7-c6c2-4d35-ab70-c55a8ab1d60b.png)

**Comment by leppott** [comment]
Added spacing for View Tidal Trends and bolded HELP for consistency.

![image](https://user-images.githubusercontent.com/24276278/179003436-8682ba3a-f48f-4d91-b1dd-ab6f53e49b95.png)

Changed shinyalert to html = TRUE and was able to use html tags to format the text.

![image](https://user-images.githubusercontent.com/24276278/179003706-7e554896-b6a6-487a-abc7-46ca8279915d.png)

**Comment by jharcum** [comment]
looks good
