### ISSUE TITLE
Change plot location

### ISSUE THREAD

**Issue by leppott** [tetratech/baytrendsmap#64]
**Is your feature request related to a problem? Please describe.**
Plots linked to map location changed from GitHub to CBP servers.

**Describe the solution you'd like**

**https://github.com/tetratech/baytrends_files/blob/main**/plots_NLT_FA_F_FP/CB1.1_do_B.png

becomes 

**https://dx3ga8blp094q.cloudfront.net**/plots_NLT_FA_F_FP/CB1.1_do_B.png

**Describe alternatives you've considered**
NA

**Additional context**
Make changes and test before deploy.

**Comment by jharcum** [comment]
looks good
