### ISSUE TITLE
07.19.2022 v1.2.1.9037 build check--more info link

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#71]
- [x] When radio button "Non-linear Trend (Short Term)" is selected, I click on a site in the map. Then I click on "More info" --> I get a 404: Not Found. (e.g., https://raw.githubusercontent.com/tetratech/baytrends_files/main/plots_NLT_FA_F_ST/ET5.1_chla_S.png)

Further notes: It seems the "No plot" message for DIN and PO4 work on all but
Same issue for Non-linear Trend with Flow Adjustment (Long Term) and Non-linear Trend with Flow Adjustment (Short Term).

**Comment by leppott** [comment]
Rework QC statement ..ifelse... to use plots_boo instead of TRUE.

![image](https://user-images.githubusercontent.com/24276278/179775014-830d3bd3-ab25-4d50-b40b-9e8313f2f5a4.png)
