### ISSUE TITLE
07.19.2022 v1.2.1.9037 build check--custom map zoom for static map 

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#72]
Pressed F5 to get fresh start.

click ok through info popup
click create custom map
click load 'final' file
click 2. filtered data
click "filter by state" > removed VA  (to focus only on MD sites)
click apply filters  
go to range map
click variable to plot > selected current mean
click auto generate title
click update range map
go to static map

.... at this point all looks good ...

![image](https://user-images.githubusercontent.com/13320765/179750989-2817b19b-9dd1-4930-865d-4bae9e1bac48.png)

click zoom region > select points
click update range map > got below error

![image](https://user-images.githubusercontent.com/13320765/179751185-38e18ddf-f439-4662-b6ce-f230f58da800.png)

**Comment by leppott** [comment]
Change from ggplot2::coord_fixed to ggplot2::coord_sf.

![image](https://user-images.githubusercontent.com/24276278/179786587-507e0b92-bf17-47e3-9a58-28ab70b2b6d1.png)

![image](https://user-images.githubusercontent.com/24276278/179786812-a0c7879c-5a75-43ac-afd1-68e62f1f4dc6.png)
