### ISSUE TITLE
Range map > Select classInt > pretty missing largest class

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#8]
**Describe the bug**
Range map > Select classInt > pretty does not appear to render classifications/legend correctly. (classInt = 'equal' works ok).  

**To Reproduce (see attached file)**
1. load/downselect to data for plotting
2. pick 5 classifications
3. pick 'pretty'
4. click update map
5. note only four symbols in legend
6. select 'equal'
7. update map
8. 5 symbols + NA in legend
9 'equal' legend includes largest value, 'pretty' is missing it
[map_pretty.docx](https://github.com/leppott/baytrendsmap/files/4582742/map_pretty.docx)

**Comment by leppott** [comment]
This one is a bit wonky.  In the test file it performed ok, in contrast to, the example above where it failed to work properly.

Pretty sometimes does its own thing and picks a different number of categories from the user input.  So it might be that need to alter the legend text.

?classInt::classIntervals

The "pretty" style chooses a number of breaks not necessarily equal to n using pretty, but likely to be legible; arguments to pretty may be passed through ….

**Comment by jharcum** [comment]
See issue #30

**Comment by jharcum** [comment]
I think solving issue #30 solved this problems NA class. Issue is placed on hold pending further testing. Leave open for now.

**Comment by jharcum** [comment]
Solving issue #8 appears to have settled this issue.
