### ISSUE TITLE
Web based version throws 'network error' when downloading map

### ISSUE THREAD

**Issue by jharcum** [tetratech/baytrendsmap#9]
Web based version throws 'network error' when downloading map (but works in RStudio Viewer)

Recreate: create any range map using web based verion. 
Click 'Save Range Map' ... error thrown,

**Comment by jharcum** [comment]
**per Breck Sullivan (5/22 email):** There is an option for you to save the maps in different formats. The only format that directly worked for me was pdf. If I wanted a png, it would never save as a png just an “all file.” I had to open it up in paint to then save it as a png. I might have been doing something wrong or it could just be my computer, but that took me a while to figure it out for a png.

**Comment by leppott** [comment]
Finally able to reproduce.

**Comment by leppott** [comment]
The map is saved in the background when click "Update Map". 

The "Save Map" button merely copies the file to the user defined location.

If the user changes the file extension between clicking these 2 buttons the operation does not complete correctly.

Possibly add some code to check the extension currently selected and the saved file.  If no match pop up a box to inform the user.

**Comment by leppott** [comment]
Error code already exists.

![image](https://user-images.githubusercontent.com/24276278/83971358-0381d080-a8a9-11ea-9bdc-c1870e53f46c.png)

Based on user comments he was probably getting the "Error_UpdateMapBeforeSave.pdf" since he mentioned only ever getting a PDF.

**Comment by leppott** [comment]
Tested both maps and all file types.  All work as intended with and without clicking update map button before save map button.  That is, when clicked update first got the intended file format and when did not got the "Error_UpdateMapBeforeSave.pdf".

**Comment by jharcum** [comment]
Test Fail. Using the app available through AWS: I created map, changed extension, clicked "update range map", waited for map to refresh, immediately clicked "save range map". I received "but_map_range_save" error

![image](https://user-images.githubusercontent.com/13320765/84064617-eb857c00-a990-11ea-8ebc-44598001862d.png)

**Comment by leppott** [comment]
Tested AWS (CBP hosted) version and was able to save all 4 files types for both maps.

Using Chrome.  Need to test with other browsers.

**Comment by leppott** [comment]
Works fine in Firefox as well.

Both Chrome and FF asked about security at the start.

Internet Explorer 11 displays another certificate warning when click "download map".  Have to click through to get to the save file dialog.

![image](https://user-images.githubusercontent.com/24276278/86245295-4452c980-bb77-11ea-9169-a22eb3edb9be.png)

**Comment by leppott** [comment]
v1.1.0.9003 is on CBT server.

https://baytrends.chesapeakebay.net/baytrendsmap/

All 4 file formats download ok with final file 1.

![image](https://user-images.githubusercontent.com/24276278/88542057-d10c6e00-cfe3-11ea-8733-3b1c6add748e.png)

![image](https://user-images.githubusercontent.com/24276278/88542101-e2ee1100-cfe3-11ea-818c-8dfd09910feb.png)

**Comment by jharcum** [comment]
done
